# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Marc Jansen'
tagline:             'Data Scientist'
description:         'Personal project page'
url:                 ''
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Marc Jansen
  url:               https://twitter.com/marcchristiaan
  email:             marc.c.jansen@gmail.com

# Custom vars
version:             1.0.0

# Social
github_username:     marccjansen
twitter_username:    marcchristiaan