url: http://marccjansen.com
# baseurl:

# Site settings
title: Marc Jansen
email: marc.c.jansen@gmail.com
description: "Personal page to feature project work and publications."


# Team names, titles and social links
people:
- name: Marc Jansen
  pic: marc
  position: Data Scientist
  social:
    - title: twitter
      url: https://twitter.com/marcchristiaan
    - title: github
      url: https://github.com/marccjansen

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty